# Generated by Django 4.0.4 on 2022-09-19 00:51

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reptile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified_at')),
                ('currentConfirmedCount', models.PositiveIntegerField(default=0, verbose_name='现存确诊人数')),
                ('confirmedCount', models.PositiveIntegerField(default=0, verbose_name='累计确诊人数')),
                ('suspectedCount', models.PositiveIntegerField(default=0, verbose_name='累计境外确诊人数')),
                ('curedCount', models.PositiveIntegerField(default=0, verbose_name='累计治愈人数')),
                ('deadCount', models.PositiveIntegerField(default=0, verbose_name='累计死亡人数')),
                ('seriousCount', models.PositiveIntegerField(default=0, verbose_name='当前无症状人数')),
                ('suspectedIncr', models.PositiveIntegerField(default=0, verbose_name='新增境外输入人数')),
                ('currentConfirmedIncr', models.PositiveIntegerField(default=0, verbose_name='相比昨天现存确诊人数')),
                ('confirmedIncr', models.PositiveIntegerField(default=0, verbose_name='\t相比昨天累计确诊人数')),
                ('curedIncr', models.PositiveIntegerField(default=0, verbose_name='相比昨天新增治愈人数')),
                ('deadIncr', models.PositiveIntegerField(default=0, verbose_name='相比昨天新增死亡人数')),
                ('seriousIncr', models.IntegerField(default=0, verbose_name='相比昨天现存无症状人数')),
                ('yesterdayConfirmedCountIncr', models.PositiveIntegerField(default=0, verbose_name='相比昨天新增累计确诊人数')),
                ('yesterdaySuspectedCountIncr', models.PositiveIntegerField(default=0, verbose_name='相比昨天境外输入确诊人数')),
                ('highDangerCount', models.PositiveIntegerField(default=0, verbose_name='国内高风险地区个数')),
                ('midDangerCount', models.PositiveIntegerField(default=0, verbose_name='国内中风险地区个数')),
            ],
            options={
                'db_table': 'reptile',
            },
        ),
    ]
