# Generated by Django 4.0.4 on 2022-09-19 00:51

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created_at')),
                ('modified_at', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified_at')),
                ('title', models.CharField(max_length=32, verbose_name='通知标题')),
                ('detail', models.CharField(max_length=125, verbose_name='检查详情')),
            ],
            options={
                'db_table': 'notices',
            },
        ),
    ]
